import React, { useState } from 'react';
import { motion } from 'framer-motion';
import heroGirl from './assets/hero-girl-clean.png';

const skills=[['React.js','Interactive interfaces'],['JavaScript','Modern web logic'],['HTML & CSS','Responsive layouts'],['Bootstrap','Rapid UI building'],['MongoDB','Document databases'],['Word','Document processing'],['SQL Server','Structured data'],['Python','Programming & analytics'],['Excel','Cleaning & analysis'],['Git & GitHub','Version control'],['Data Analytics','Insights & visualization']];
const projects=[
 ['Lost & Found Platform','React • Node • Express • MongoDB','Final year platform for reporting, searching and managing lost/found persons and items.','https://github.com/Farwa07/Lost-and-Found','01'],
 ['Contracting Business Website','MERN • Vercel','Responsive business website for contracting and general maintenance services.','https://farhan-izhar-contracting.vercel.app/','02'],
 ['Coding Blog','Bootstrap • CSS','Responsive coding blog with structured content and a clean reading experience.','https://blog-coding-six.vercel.app/','03'],
 ['Amazon Clone','HTML • CSS','Amazon-inspired responsive e-commerce landing page built to practice modern layouts.','https://amazon-clone-peach-theta.vercel.app/','04']
];
const Reveal=({children,className=''})=><motion.div className={className} initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.16}} transition={{duration:.65,ease:'easeOut'}}>{children}</motion.div>;

export default function App(){
const [menuOpen,setMenuOpen]=useState(false);
return <main>
<nav><a className="brand" href="#home">FARWA<span>.</span></a><div className={`navlinks ${menuOpen?'open':''}`}><a onClick={()=>setMenuOpen(false)} href="#home">Home</a><a onClick={()=>setMenuOpen(false)} href="#about">About</a><a onClick={()=>setMenuOpen(false)} href="#skills">Skills</a><a onClick={()=>setMenuOpen(false)} href="#work">Projects</a><a onClick={()=>setMenuOpen(false)} href="#experience">Experience</a><a onClick={()=>setMenuOpen(false)} href="#contact">Contact</a></div><div className="navRight"><a className="github" href="https://github.com/Farwa07" target="_blank" rel="noreferrer"><span>●</span> GitHub</a><button className={`menuBtn ${menuOpen?'active':''}`} onClick={()=>setMenuOpen(v=>!v)} aria-label="Toggle menu"><i/><i/><i/></button></div></nav>

<section id="home" className="hero">
 <div className="heroArt"><img src={heroGirl} alt="3D developer working on a laptop" /></div>
 <div className="heroGlow"/><Reveal className="heroCopy"><p className="eyebrow">HELLO, I'M</p><h1>Farwa<br/><em>Izhar.</em></h1><h2>Front-End Developer <i>×</i> Data Analyst</h2><p className="lead">I build clean digital experiences and turn data into useful insights — with a focus on responsive interfaces, React and modern web development.</p><div className="actions"><a className="primary" href="#work">View My Work <b>→</b></a><a className="secondary" href="/public-resume.pdf" download>↓ Download Resume</a></div></Reveal><div className="scroll">SCROLL <span>⌄</span></div>
</section>

<section id="about" className="about section"><div className="aboutScene"><div className="sceneOrb orbA"/><div className="sceneOrb orbB"/><div className="glassWindow"><div className="windowDots">● ● ●</div><div className="codeLine w85"/><div className="codeLine w55"/><div className="codeLine w72"/><div className="codeLine w42"/><div className="codeLine w65"/></div><div className="cube cube1">&lt;/&gt;</div><div className="cube cube2">JS</div><div className="deskCard"><span>creative</span><b>developer</b><small>code • design • data</small></div></div><Reveal className="sectionCopy"><p className="eyebrow">01 / ABOUT ME</p><h3>I turn ideas into<br/><em>digital experiences.</em></h3><p>I'm a BS Information Technology graduate focused on front-end web development and data analytics. I enjoy combining clean design with practical code to build responsive, useful experiences.</p><div className="miniStats"><div><strong>BSIT</strong><span>IT Graduate</span></div><div><strong>5+</strong><span>Projects</span></div><div><strong>MERN</strong><span>Web Stack</span></div></div></Reveal></section>

<section id="skills" className="skills section"><Reveal className="centerHead"><p className="eyebrow">02 / MY TOOLKIT</p><h3>Tools I use to <em>build.</em></h3><p>From interface development to data work, these are the technologies behind my projects.</p></Reveal><div className="skillGrid">{skills.map(([name,desc],i)=><motion.div className="skillCard" key={name} whileHover={{y:-9,rotateX:4,rotateY:i%2?4:-4}}><div className="skillIcon">{name.slice(0,2).toUpperCase()}</div><div><b>{name}</b><span>{desc}</span></div><small>{String(i+1).padStart(2,'0')}</small></motion.div>)}</div></section>

<section id="work" className="projects section"><Reveal><p className="eyebrow">03 / FEATURED PROJECTS</p><h3>Things I've <em>built.</em></h3></Reveal><div className="projectGrid">{projects.map((p,i)=><motion.a href={p[3]} target="_blank" rel="noreferrer" className="projectCard" key={p[0]} whileHover={{y:-10}}><div className={`projectVisual pv${i+1}`}><span className="projectNo">{p[4]}</span><div className="mockBrowser"><i/><i/><i/><div className="mockContent"><div/><div/><div/></div></div></div><div className="projectInfo"><small>{p[1]}</small><h4>{p[0]}</h4><p>{p[2]}</p><b>View project ↗</b></div></motion.a>)}</div></section>

<section id="experience" className="experience section"><Reveal className="sectionCopy"><p className="eyebrow">04 / EXPERIENCE</p><h3>Learning through<br/><em>real work.</em></h3><div className="timeline"><div><span>Experience</span><b>Junior Web Developer</b><small>Softix AI Solutions</small><p>Worked on real-world web projects and strengthened practical JavaScript, React.js and front-end development skills.</p></div><div><span>Education</span><b>BS Information Technology</b><small>Government Post Graduate Islamia College</small><p>Built a foundation across web development, databases, programming and data analytics.</p></div></div></Reveal><div className="experienceScene"><div className="ring r1"/><div className="ring r2"/><div className="floatingPanel panelCode"><span>PROJECT.JSX</span><div/><div/><div/><div/></div><div className="floatingPanel panelData"><span>DATA</span><b>78%</b><i/><i/><i/></div><div className="core3d"><span>FI</span></div></div></section>

<section id="contact" className="contact section"><div className="contactGlow"/><Reveal className="contactBox"><p className="eyebrow">05 / LET'S CONNECT</p><h3>Have an idea?<br/><em>Let's create it.</em></h3><p>I'm open to front-end, web development and data-focused opportunities.</p><div className="contactLinks"><a href="mailto:farwwaaa@gmail.com"><span>✉</span><div><small>Email</small><b>farwwaaa@gmail.com</b></div></a><a href="https://github.com/Farwa07" target="_blank" rel="noreferrer"><span>⌘</span><div><small>GitHub</small><b>Farwa07</b></div></a><div><span>⌖</span><div><small>Location</small><b>Gujranwala, Pakistan</b></div></div></div></Reveal><div className="contactArt"><div className="planet"><span>F.</span></div><div className="orbit one"/><div className="orbit two"/><div className="spark s1"/><div className="spark s2"/><div className="spark s3"/></div></section>
<footer><b>FARWA<span>.</span></b><p>Designed & built with React</p><p>© 2026 Farwa Izhar</p></footer>
</main>}
